name: kos_hunter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  supabase_flutter: ^1.10.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_new2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/bottom.png
    - assets/logo.png
    - assets/image_10.png
    - assets/image_11.png
    - assets/pic_14.png
    - assets/Icon_star_solid.png
    - assets/image_14.png
    - assets/pic_13.png
    - assets/pic_12.png
    - assets/icon_2.png
    - assets/icon_3.png
    - assets/Icon_home_solid.png
    - assets/Icon_love_solid.png
    - assets/Icon_mail_solid.png
    - assets/Icon_card_solid.png
    - assets/pic_18.png
    - assets/btn_back.png
    - assets/btn_wishlist.png
    - assets/001_bar_counter.png
    - assets/002_double_bed.png
    - assets/003_cupboard.png
    - assets/pic_19.png
    - assets/pic_20.png
    - assets/pic_22.png
    - assets/btn_wishlist_1.png
    - assets/404.png
    - assets/logo_new2.png
    - assets/splash_screen.png
    - assets/screen.png
    - assets/google.png